---
####################
# deploy
####################
kube_apiserver_deploy_path: "{{ k8s_server_download_path }}"

####################
# config
####################

kube_apiserver_bin_path: "/usr/bin"
#kube_apiserver_config_path: "{{ k8s_config_directory }}/kubeserver"
kube_apiserver_config_path: "{{ k8s_config_directory }}/apiserver"
kube_apiserver_cert_path: "{{ kube_apiserver_config_path }}/pki"
kube_apiserver_log_path: "{{ k8s_log_path }}/apiserver"

kube_server_services:
  - binary_name: "kube-apiserver"
  - binary_name: "kube-controller-manager"
  - binary_name: "kube-scheduler"

kube_api_args:
  - "--authorization-mode=Node,RBAC"
  - "--enable-bootstrap-token-auth=true"
  - "--kubelet-client-certificate={{ kube_apiserver_cert_path }}/apiserver-kubelet-client.crt"
  - "--kubelet-client-key={{ kube_apiserver_cert_path }}/apiserver-kubelet-client.key"
  - "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname"
  - "--proxy-client-cert-file={{ kube_apiserver_cert_path }}/front-proxy-client.crt"
  - "--proxy-client-key-file={{ kube_apiserver_cert_path }}/front-proxy-client.key"
  - "--requestheader-allowed-names=front-proxy-client"
  - "--requestheader-client-ca-file={{ kube_apiserver_cert_path }}/front-proxy-ca.crt"
  - "--requestheader-extra-headers-prefix=X-Remote-Extra"
  - "--requestheader-group-headers=X-Remote-Group"
  - "--requestheader-username-headers=X-Remote-User"
  - "--secure-port=6443"
  - "--service-account-key-file={{ kube_apiserver_cert_path }}/sa.pub"
  - "--feature-gates=BlockVolume=true,CSIBlockVolume=true,CSIPersistentVolume=true,MountPropagation=true,VolumeSnapshotDataSource=true,KubeletPluginsWatcher=true,CSINodeInfo=true,CSIDriverRegistry=true"
  - "--log-dir={{ kube_apiserver_log_path }}"

kube_controller_manager_args:
  - "--address=127.0.0.1"
  - "--authentication-kubeconfig={{ kube_apiserver_config_path }}/controller-manager.kubeconfig"
  - "--authorization-kubeconfig={{ kube_apiserver_config_path }}/controller-manager.kubeconfig"
  - "--client-ca-file={{ kube_apiserver_cert_path }}/ca.crt"
  - "--cluster-signing-cert-file={{ kube_apiserver_cert_path }}/ca.crt"
  - "--cluster-signing-key-file={{ kube_apiserver_cert_path }}/ca.key"
  - "--controllers=*,bootstrapsigner,tokencleaner"
  - "--kubeconfig={{ kube_apiserver_config_path }}/controller-manager.kubeconfig"
  - "--requestheader-client-ca-file={{ kube_apiserver_cert_path }}/front-proxy-ca.crt"
  - "--use-service-account-credentials=true"
  - "--feature-gates=BlockVolume=true,CSIBlockVolume=true"
  - "--log-dir={{ kube_apiserver_log_path }}"

kube_scheduler_args:
  - "--address=127.0.0.1"
  - "--kubeconfig={{ kube_apiserver_config_path }}/scheduler.kubeconfig"
  - "--feature-gates=BlockVolume=true,CSIBlockVolume=true"
  - "--log-dir={{ kube_apiserver_log_path }}"
