---
- name: Check if the etcd process is running
  shell: ps -ef | grep -w "/usr/bin/etcd"| grep -v grep | wc -l
  register: check_etcd_process
  check_mode: no
  ignore_errors: yes
  changed_when: no

- debug: var=check_etcd_process verbosity={{ debug_level }}
