---
- name: Ensuring flannel config path exist
  file:
    path: "{{ flannel_config_path }}"
    state: "directory"
    mode: "0770"
  become: true

- name: Distribute certificates to flannel nodes
  copy:
    src: "{{ deploy_k8s_cert_path }}/{{ item }}"
    dest: "{{ flannel_config_path }}/{{ item }}"
  become: true
  with_items:
    - "etcd-ca.crt"
    - "etcd-ca.key"
    - "etcd-server.crt"
    - "etcd-server.key"
