---
- name: Check kubelet.kubeconfig file
  stat:
    path: "{{ deploy_k8s_cert_path }}/kubelet.kubeconfig"
  register: check_kubelet_config
  become: true

- name: Show check_kubelet_config info
  debug: msg="The kubelet.kubeconfig exists stat is {{ check_kubelet_config.stat.exists }}" verbosity={{ debug_level }}
