---
- name: Check the kubelet service is running
  shell: ps -ef | grep -w {{kubelet_bin_path}}/kubelet | grep -v grep | wc -l
  register: check_kubelet_process
  check_mode: no
  ignore_errors: yes
  changed_when: no

- debug: var=check_kubelet_process verbosity={{ debug_level }}

- name: Check the kube-proxy service is running
  shell: ps -ef | grep -w {{kubelet_bin_path}}/kube-proxy | grep -v grep | wc -l
  register: check_proxy_process
  check_mode: no
  ignore_errors: yes
  changed_when: no

- debug: var=check_proxy_process verbosity={{ debug_level }}