---
- include_tasks: check_docker.yml

- name: Modify the docker configuration EnvironmentFile
  shell: sed -i '/^\[Service\]/a EnvironmentFile=-\/run\/flannel\/docker/' /usr/lib/systemd/system/docker.service
  become: true
  register: set_docker_env
  when: check_docker_env.rc != 0

- name: Modify the docker configuration ExecStart
  shell: sed -i 's/^ExecStart=.*/ExecStart=\/usr\/bin\/dockerd $DOCKER_OPTS/' /usr/lib/systemd/system/docker.service
  become: true
  register: set_docker_exec
  when: check_docker_exec.rc != 0

- name: Modify the docker configuration After
  shell: sed -i 's/^After=.*/After=network-online.target firewalld.service containerd.service flanneld.service/' /usr/lib/systemd/system/docker.service
  become: true
  register: set_docker_after
  when: check_docker_after.rc != 0

- name: Modify the docker configuration Requires
  shell: sed -i 's/^Requires=.*/Requires=flanneld.service/' /usr/lib/systemd/system/docker.service
  become: true
  register: set_docker_requires
  when: check_docker_requires.rc != 0

- name: Restart docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  become: true
  when:
    - (set_docker_env.changed | bool) or
      (set_docker_exec.changed | bool) or
      (set_docker_after.changed | bool) or
      (set_docker_requires.changed | bool)
